(()=>{
'use strict';
const CONTRACT='data/site/historical_betting_analytics_v2.json',ORDER_FALLBACK=[],$=id=>document.getElementById(id),pct=v=>v==null?'N/A':(Number(v)*100).toFixed(1)+'%',signed=(v,d=2)=>v==null?'N/A':(Number(v)>0?'+':'')+Number(v).toFixed(d),esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));let C;
const models=m=>C.models.filter(x=>x.market_type===m&&x.historical_validation!=='LIMITED_PROVENANCE_NOT_EQUIVALENT'),rows=(m,id)=>C.independent_checkpoint_performance.filter(x=>x.market_type===m&&x.model_id===id);
function table(market,title){const root=[...document.querySelectorAll('.histCard')].find(x=>x.querySelector('h2')?.textContent.trim()===title);if(!root)return;const box=document.createElement('div');box.className='histInlineControls';box.innerHTML='<select aria-label="Historical model"></select><select aria-label="Historical checkpoint"></select>';root.querySelector('.histHead>div').appendChild(box);const ms=box.children[0],cs=box.children[1];ms.innerHTML=models(market).map(x=>`<option value="${esc(x.model_id)}">${esc(x.label)}</option>`).join('');ms.value=C.default_selection[market].model_id;
 function checkpoints(){const have=[...new Set(rows(market,ms.value).map(x=>x.checkpoint))];cs.innerHTML=C.checkpoint_order.filter(x=>have.includes(x)).map(x=>`<option value="${x}">${x.replaceAll('_',' ')}</option>`).join('');cs.value=have.includes(C.default_selection[market].checkpoint)?C.default_selection[market].checkpoint:have[0];render()}
 function render(){const data=rows(market,ms.value).filter(x=>x.checkpoint===cs.value).sort((a,b)=>a.threshold-b.threshold),body=root.querySelector('tbody'),model=C.models.find(x=>x.model_id===ms.value);body.innerHTML=data.map(r=>`<tr class="${r.threshold===3?'histActionRow':''} ${r.sample_strength==='VERY_SMALL_INSUFFICIENT'?'histTinySample':''}" title="Sample strength: ${esc(r.sample_strength||'unclassified')}"><td><b>${r.threshold}+</b></td><td>${r.n.toLocaleString()}</td><td>${esc(r.record)}</td><td>${pct(r.win_pct)}</td><td class="${Number(r.roi)>=0?'histPositive':'histNegative'}">${pct(r.roi)}</td><td>${pct(r.beat_close_pct)}</td><td>${pct(r.won_line_move_pct)}</td><td class="histEmphasis">${signed(r.avg_clv)}</td><td>N/A</td></tr>`).join('')||'<tr><td colspan="9">No preserved sample at this checkpoint.</td></tr>';root.querySelector('.histHead small').textContent=`2021–2025 · ${model.label} · ${cs.value.replaceAll('_',' ')} · ${data[0]?.sample_classification||'preserved sample'}`}
 ms.onchange=checkpoints;cs.onchange=render;checkpoints()}
const METRICS={independent:{win_pct:'ATS / O-U Win %',roi:'ROI',avg_clv:'Avg CLV',beat_close_pct:'Beat Close %',won_line_move_pct:'Won Line Move %',n:'Sample N',avg_edge:'Average Edge'},matched:{mean_remaining_edge:'Mean Remaining Edge',remaining_edge_pct:'Original Edge Remaining %',edge_persistence_pct:'Threshold Persistence %',positive_edge_persistence_pct:'Positive-Edge Persistence %',same_side_persistence_pct:'Same-Side Persistence %',reversal_pct:'Reversal %',roi:'Origin Wager ROI',avg_clv:'Origin Wager Avg CLV',n:'Sample N'}};
function options(el,items,value){el.innerHTML=items.map(x=>`<option value="${esc(x.value)}">${esc(x.label)}</option>`).join('');if(value!=null)el.value=value}
function graph(){const market=$('decayMarket'),model=$('decayModel'),threshold=$('decayThreshold'),mode=$('decayMode'),origin=$('decayOrigin'),metric=$('decayMetric');
 function resetModels(){options(model,models(market.value).map(x=>({value:x.model_id,label:x.label})),C.default_selection[market.value].model_id);resetThresholds()}
 function resetThresholds(){const x=[...new Set(rows(market.value,model.value).map(r=>r.threshold))].sort((a,b)=>a-b);options(threshold,x.map(v=>({value:v,label:v+'+'})),C.default_selection[market.value].threshold);resetOrigins()}
 function resetOrigins(){const x=[...new Set(C.matched_signal_decay.filter(r=>r.market_type===market.value&&r.model_id===model.value&&Number(r.threshold)===Number(threshold.value)).map(r=>r.origin_checkpoint))];options(origin,x.map(v=>({value:v,label:'Origin '+v.replaceAll('_',' ')})),x.includes(C.default_selection[market.value].checkpoint)?C.default_selection[market.value].checkpoint:x[0]);resetMetrics()}
 function resetMetrics(){options(metric,Object.entries(METRICS[mode.value]).map(([value,label])=>({value,label})),mode.value==='independent'?'roi':'edge_persistence_pct');origin.hidden=mode.value!=='matched';render()}
 function render(){let data=mode.value==='independent'?rows(market.value,model.value).filter(r=>Number(r.threshold)===Number(threshold.value)):C.matched_signal_decay.filter(r=>r.market_type===market.value&&r.model_id===model.value&&Number(r.threshold)===Number(threshold.value)&&r.origin_checkpoint===origin.value);data=data.filter(r=>r[metric.value]!=null);if(!data.length){$('decayChart').innerHTML='<div class="modelEmpty">No preserved sample for this selection.</div>';return}const order=C.checkpoint_order,W=920,H=250,pad=42,idx=r=>order.indexOf(r.checkpoint),vals=data.map(r=>Number(r[metric.value])),lo=Math.min(...vals),hi=Math.max(...vals),range=hi-lo||1,x=r=>pad+idx(r)*(W-pad*2)/(order.length-1),y=v=>H-pad-(v-lo)/range*(H-pad*2),map=new Map(data.map(r=>[idx(r),r]));let lines='';for(let i=0;i<order.length-1;i++)if(map.has(i)&&map.has(i+1)){const a=map.get(i),b=map.get(i+1);lines+=`<line class="decayLine" x1="${x(a)}" y1="${y(a[metric.value])}" x2="${x(b)}" y2="${y(b[metric.value])}"/>`}const isPct=['win_pct','roi','beat_close_pct','won_line_move_pct','remaining_edge_pct','edge_persistence_pct','positive_edge_persistence_pct','same_side_persistence_pct','reversal_pct'].includes(metric.value),points=data.map(r=>{const v=Number(r[metric.value]),display=metric.value==='n'?r.n.toLocaleString():isPct?pct(v):signed(v);return `<g><circle class="decayPoint" cx="${x(r)}" cy="${y(v)}" r="5"/><text class="decayValue" x="${x(r)}" y="${y(v)-10}" text-anchor="middle">${display}</text><text class="decayLabel" x="${x(r)}" y="${H-12}" text-anchor="middle">${r.checkpoint.replaceAll('_ET','').replaceAll('_',' ')}</text><text class="decayLabel" x="${x(r)}" y="${y(v)+18}" text-anchor="middle">N ${r.n}</text></g>`}).join('');$('decayChart').innerHTML=`<svg viewBox="0 0 ${W} ${H}" preserveAspectRatio="none"><line class="decayAxis" x1="${pad}" y1="${H-pad}" x2="${W-pad}" y2="${H-pad}"/>${lines}${points}</svg>`;$('decayCoverage').textContent=market.value==='spread'?C.coverage.spread:C.coverage.total;$('decayNote').textContent=(mode.value==='independent'?'Fresh signals are independently selected at each checkpoint.':'Matched origin cohort keeps the original game, wager side, line, and threshold fixed through later checkpoints.')+' CLV-implied EV remains N/A without validated calibration.'}
 market.onchange=resetModels;model.onchange=resetThresholds;threshold.onchange=resetOrigins;mode.onchange=resetMetrics;origin.onchange=render;metric.onchange=render;resetModels()}
fetch(CONTRACT).then(r=>{if(!r.ok)throw Error(r.status);return r.json()}).then(x=>{C=x;table('spread','Historical Spread Edge Validation');table('total','Historical Totals Edge Validation');graph()}).catch(e=>{$('decayChart').innerHTML=`<div class="modelEmpty">Historical analytics unavailable: ${esc(e.message)}</div>`});
})();
