(function(root,factory){const api=factory();if(typeof module==='object'&&module.exports)module.exports=api;else root.FuturesDashboard=api})(typeof globalThis!=='undefined'?globalThis:this,function(){
'use strict';
const MODES={wins:{domain:'win',edge:'win_edge'},title:{domain:'conference_title',edge:'title_edge'},cfp:{domain:'make_cfp',edge:'playoff_edge'},national:{domain:'national_title',edge:'national_title_edge'}},BOOKS=['DraftKings','FanDuel','BetMGM','Caesars'];
const hasNumber=v=>v!==null&&v!==undefined&&v!==''&&Number.isFinite(Number(v));
const focusMode=s=>s.mode==='playoff'?(s.playoffFocus==='title'?'national':'cfp'):s.mode;
function spec(mode){return MODES[mode]||MODES.wins}function currentEdge(row,mode){const v=row?.[spec(mode).edge];return hasNumber(v)?Number(v):null}
function delta(row,mode,period,key='edge'){const v=row?.[period==='day'?'delta_day':'delta_week']?.[spec(mode).domain]?.[key];return hasNumber(v)?Number(v):null}
function priorEdge(row,mode,period){const now=currentEdge(row,mode),change=delta(row,mode,period);return now===null||change===null?null:now-change}
function deltas(row,mode,period){return row?.[period==='day'?'delta_day':'delta_week']?.[spec(mode).domain]||{}}
function metric(row,mode,period,key){return key==='edge'?currentEdge(row,mode):key==='edge_change'?delta(row,mode,period):delta(row,mode,period,key==='model_change'?'model':'market')}
function quoteFor(quotes,book){return quotes?.[book]||null}function isBestBook(row,mode,book){return row?.[{wins:'win_book',title:'title_book',cfp:'playoff_book',national:'national_title_book'}[mode]]===book}
function resolveSchedule(row,scheduleGames){return(row?.schedule_game_ids||[]).map(id=>{const g=scheduleGames?.[id];if(!g)return null;const isHome=row.team===g.home_team,own=isHome?g.home_score:g.away_score,opp=isHome?g.away_score:g.home_score,win=g.home_win_probability;return{game_id:id,week:g.week,date:g.date,opponent:isHome?g.away_team:g.home_team,site:g.neutral_site?'N':isHome?'HOME':'AWAY',completed:Boolean(g.completed),team_score:own,opponent_score:opp,result:g.completed&&hasNumber(own)&&hasNumber(opp)&&Number(own)!==Number(opp)?(Number(own)>Number(opp)?'W':'L'):null,win_probability:g.completed?null:isHome?win:hasNumber(win)?1-Number(win):null}}).filter(Boolean)}
function historySlots(row,domain,axis,baselineDate,currentWeek){const keys={win:['model_projected_wins','market_win_total'],conference_title:['conference_title_model_prob','conference_title_market_prob'],make_cfp:['cfp_model_prob','cfp_market_prob'],national_title:['national_title_model_prob','national_title_market_prob']}[domain],slots=(axis||[]).map(label=>({label,model:null,market:null}));for(const p of row.history||[]){const label=p.checkpoint_date===baselineDate?'Pre-W1':null,i=slots.findIndex(x=>x.label===label);if(i>=0){slots[i].model=hasNumber(p[keys[0]])?Number(p[keys[0]]):null;slots[i].market=hasNumber(p[keys[1]])?Number(p[keys[1]]):null}}const c=domain==='win'?[row.projected_wins,row.market_win_total]:domain==='conference_title'?[row.title_model_prob,row.title_market_prob]:domain==='make_cfp'?[row.playoff_model_prob,row.playoff_market_prob]:[row.national_title_model_prob,row.national_title_market_prob],i=slots.findIndex(x=>x.label===`W${currentWeek}`);if(i>=0){slots[i].model=hasNumber(c[0])?Number(c[0]):null;slots[i].market=hasNumber(c[1])?Number(c[1]):null}return slots}
function qualifies(row,state){const mode=focusMode(state),edge=currentEdge(row,mode),change=delta(row,mode,state.period),prior=priorEdge(row,mode,state.period);if(state.view==='growing'&&!(change>0))return false;if(state.view==='shrinking'&&!(change<0))return false;if(state.view==='crossed'&&!(prior!==null&&prior<=0&&edge>0))return false;if(state.edgeStatus==='positive'&&!(edge>0))return false;if(state.edgeStatus==='negative'&&!(edge<0))return false;if(state.edgeStatus==='growing'&&!(change>0))return false;if(state.edgeStatus==='shrinking'&&!(change<0))return false;if(state.edgeStatus==='crossed_positive'&&!(prior!==null&&prior<=0&&edge>0))return false;if(state.edgeStatus==='crossed_negative'&&!(prior!==null&&prior>=0&&edge<0))return false;return true}
function queryRows(rows,state){const q=String(state.search||'').trim().toLowerCase(),mode=focusMode(state),result=rows.filter(row=>(state.mode!=='bets'||(row.open_wagers||[]).length)&&(state.conference==='all'||row.conference===state.conference)&&(!q||String(row.team||'').toLowerCase().includes(q))&&(state.mode==='bets'||qualifies(row,state)));const metric=row=>state.sort==='team'?row.team:state.sort==='conference'?row.conference:state.sort==='edge_change'?delta(row,mode,state.period):state.sort==='model_change'?delta(row,mode,state.period,'model'):state.sort==='market_change'?delta(row,mode,state.period,'market'):currentEdge(row,mode);result.sort((a,b)=>{let av=metric(a),bv=metric(b);if(typeof av==='string'||typeof bv==='string')return String(av||'').localeCompare(String(bv||''));if(state.view==='movers'&&state.sort==='edge_change'){av=hasNumber(av)?Math.abs(av):null;bv=hasNumber(bv)?Math.abs(bv):null}if(av===null&&bv===null)return String(a.team).localeCompare(String(b.team));if(av===null)return 1;if(bv===null)return-1;return(bv-av)||String(a.team).localeCompare(String(b.team))});return result}
function summary(rows,state){const mode=focusMode(state),numeric=rows.filter(r=>currentEdge(r,mode)!==null),gains=rows.filter(r=>delta(r,mode,state.period)!==null).sort((a,b)=>delta(b,mode,state.period)-delta(a,mode,state.period));return{shown:rows.length,positive:numeric.filter(r=>currentEdge(r,mode)>0).length,biggest:numeric.sort((a,b)=>currentEdge(b,mode)-currentEdge(a,mode))[0]||null,biggestGain:gains[0]||null}}
return{BOOKS,hasNumber,spec,focusMode,currentEdge,delta,deltas,metric,priorEdge,quoteFor,isBestBook,resolveSchedule,historySlots,qualifies,queryRows,summary};
});

(function(){'use strict';if(typeof document==='undefined')return;const F=window.FuturesDashboard,BOOKS=F.BOOKS;let state={conference:'all',view:'all',period:'week',search:'',sort:'edge',edgeStatus:'all',mode:'wins',playoffFocus:'cfp',team:null,railTab:'overview',historyMetric:'futures'},originalRender=null,activeTeam=null;const esc=x=>String(x??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c])),num=(x,d=1)=>F.hasNumber(x)?Number(x).toFixed(d):'—',percent=x=>F.hasNumber(x)?`${(Number(x)*100).toFixed(1)}%`:'—',odds=x=>F.hasNumber(x)?`${Number(x)>0?'+':''}${Math.round(Number(x))}`:'—';
function controls(){const cs=[...new Set(D.rows.map(r=>r.conference).filter(Boolean))].sort(),s=document.createElement('section');s.className='dashboardControls';s.id='dashboardControls';s.innerHTML=`<label>Conference<select id="dashConference"><option value="all">All</option>${cs.map(c=>`<option>${esc(c)}</option>`).join('')}</select></label><label>View<select id="dashView"><option value="all">All</option><option value="best">Best Edges</option><option value="movers">Biggest Movers</option><option value="growing">Growing</option><option value="shrinking">Shrinking</option><option value="crossed">Crossed Positive</option></select></label><label>Change<select id="dashPeriod"><option value="week">Week</option><option value="day">Day</option></select></label><label>Edge status<select id="dashEdgeStatus"><option value="all">All</option><option value="positive">Positive</option><option value="negative">Negative</option><option value="growing">Growing</option><option value="shrinking">Shrinking</option><option value="crossed_positive">Crossed +</option><option value="crossed_negative">Crossed −</option></select></label><label>Sort<select id="dashSort"><option value="edge">Edge</option><option value="edge_change">Edge Change</option><option value="model_change">Model Change</option><option value="market_change">Market Change</option><option value="team">Team</option><option value="conference">Conference</option></select></label><label class="searchControl">Team search<input id="dashSearch" type="search" placeholder="Find a team"></label><button id="dashReset" class="resetButton">Reset</button>`;return s}
const modeKey=()=>F.focusMode(state),kindPrefix=k=>k==='wins'?'win':k==='title'?'title':k==='cfp'?'playoff':'national_title';
function move(v,prob=false){if(!F.hasNumber(v))return'<span class="dashDelta unavailable">—</span>';v=Number(v)*(prob?100:1);return`<span class="dashDelta ${v>0?'moveUp':v<0?'moveDown':'neutral'}">${v>0?'↑':v<0?'↓':'→'} ${v>0?'+':''}${v.toFixed(1)}${prob?' pts':''}</span>`}
function rating(x){if(!F.hasNumber(x.team_rating))return'—';const d=x.team_rating_delta_week;return`<b>${num(x.team_rating)}</b>${F.hasNumber(d)?` <small class="${d>0?'moveUp':d<0?'moveDown':'neutral'}">${d>0?'↑':d<0?'↓':'→'} ${d>0?'+':''}${num(d)}</small>`:''}`}
function teamCell(x){return`<td class="teamColumn"><button class="teamOpen" data-team="${esc(x.team)}">${logo(x)}<span><b>${esc(x.team)}</b><small>${esc(x.conference||'IND')} ${x.record?.wins??'—'}-${x.record?.losses??'—'}</small></span></button></td>`}
function quoteCell(x,book,kind){const q=F.quoteFor(x[`${kindPrefix(kind)}_quotes`],book),best=F.isBestBook(x,kind,book);if(!q)return`<td class="bookQuote missing" data-label="${book}">—</td>`;const side=kind==='wins'?x.win_direction:'Win',price=kind==='wins'?(side==='Under'?q.under_price:q.over_price):q.price,primary=kind==='wins'?num(q.number):percent(q.implied_probability);return`<td class="bookQuote${best?' bestBook':''}" data-label="${book}" title="${esc(book)} · ${esc(side)}${best?' · selected best executable quote':''}"><span>${primary}</span><b>${odds(price)}</b>${best?'<i aria-label="Best executable">●</i>':''}</td>`}
function modelValue(x,k){return k==='wins'?num(x.projected_wins):k==='title'?percent(x.title_model_prob):k==='cfp'?percent(x.playoff_model_prob):percent(x.national_title_model_prob)}
function edgeValue(x,k){const v=F.currentEdge(x,k),d=F.delta(x,k,state.period),side=k==='wins'?(x.win_direction==='Over'?'O ':x.win_direction==='Under'?'U ':''):'';return`<span class="${v===null?'neutral':v>=0?'good':'bad'}">${side}${v!==null&&v>0?'+':''}${k==='wins'?num(v):`${v===null?'—':(v*100).toFixed(1)} pts`}</span>${move(d,k!=='wins')}`}
const wager=x=>x.open_wagers?.length?`<span class="bet">BET ${x.open_wagers.length}</span>`:'<span class="bet betEmpty">BET</span>';
function focus(){return`<div id="playoffFocus" class="focus"><button data-focus="cfp" class="${state.playoffFocus==='cfp'?'active':''}">CFP</button><button data-focus="title" class="${state.playoffFocus==='title'?'active':''}">TITLE</button><button disabled title="Focused mode preserves readable columns at 1280px">BOTH</button><small>BOTH deferred: focused mode keeps four books readable.</small></div>`}
function renderTable(a){if(state.mode==='bets'){originalRender();return}const k=modeKey();head.innerHTML=`<tr><th>Team</th><th>Rating</th><th>Model</th>${BOOKS.map(b=>`<th class="bookHead">${b==='DraftKings'?'DK':b==='FanDuel'?'FD':b==='BetMGM'?'MGM':'CZR'}</th>`).join('')}<th>Edge</th>${state.mode==='playoff'?'<th>Path</th>':''}<th class="wagerHead">Wager</th></tr>`;rows.innerHTML=a.map(x=>`<tr data-row-team="${esc(x.team)}">${teamCell(x)}<td data-label="Rating" class="ratingCell">${rating(x)}</td><td data-label="Model" class="modelCell"><b>${modelValue(x,k)}</b></td>${BOOKS.map(b=>quoteCell(x,b,k)).join('')}<td data-label="Edge" class="edgeCell">${edgeValue(x,k)}</td>${state.mode==='playoff'?`<td data-label="Path">${pathButton(x)}</td>`:''}<td data-label="Wager" class="wagerCell">${wager(x)}</td></tr>`).join('')}
function marketRow(label,model,market,edge){return`<div><span>${label}</span><b>${model}</b><b>${market}</b><b class="${edge>=0?'good':'bad'}">${F.hasNumber(edge)?`${edge>0?'+':''}${label==='Win total'?num(edge):`${(edge*100).toFixed(1)} pts`}`:'—'}</b></div>`}
function overview(x){return`<div class="overviewHead"><span>Market</span><b>Model</b><b>Market</b><b>Edge</b></div>${marketRow('Win total',num(x.projected_wins),num(x.market_win_total),x.win_edge)}${marketRow('Conference',percent(x.title_model_prob),percent(x.title_market_prob),x.title_edge)}${marketRow('CFP',percent(x.playoff_model_prob),percent(x.playoff_market_prob),x.playoff_edge)}${marketRow('National title',percent(x.national_title_model_prob),percent(x.national_title_market_prob),x.national_title_edge)}`}
function schedule(x){const games=F.resolveSchedule(x,D.schedule_games);return`<div class="scheduleHeader"><span>WK</span><span>DATE</span><span>OPP / SITE</span><span>STATUS</span><span>WIN %</span></div>${games.map(g=>`<div class="scheduleRow"><b>${g.week??'—'}</b><span>${esc(g.date?.slice(5)||'—')}</span><span><b>${esc(g.opponent)}</b><small>${g.site}</small></span><span>${g.completed?`${g.result||'F'} ${num(g.team_score,0)}-${num(g.opponent_score,0)}`:'UPCOMING'}</span><b>${g.completed?'—':percent(g.win_probability)}</b></div>`).join('')||'<p class="railEmpty">Schedule unavailable.</p>'}`}
function chart(x){if(state.historyMetric==='rating')return ratingHistory(x);const k=modeKey(),prob=k!=='wins',slots=F.historySlots(x,F.spec(k).domain,D.history_axis?.labels,D.weekly_baseline?.checkpoint_date,D.history_axis?.current_week),values=slots.flatMap(p=>[p.model,p.market]).filter(F.hasNumber).map(v=>Number(v)*(prob?100:1));if(!values.length)return'<p class="railEmpty">History unavailable; missing values remain gaps.</p>';let min=Math.min(...values),max=Math.max(...values);if(min===max){min-=1;max+=1}const w=560,h=190,l=44,r=10,t=12,b=36,px=i=>l+i*(w-l-r)/Math.max(1,slots.length-1),py=v=>t+(max-v)*(h-t-b)/(max-min),segments=key=>{let paths=[],part=[];slots.forEach((p,i)=>{if(F.hasNumber(p[key]))part.push(`${px(i)},${py(Number(p[key])*(prob?100:1))}`);else if(part.length){paths.push(part);part=[]}});if(part.length)paths.push(part);return paths.map(a=>`<polyline points="${a.join(' ')}"></polyline>`).join(' ')},points=key=>slots.map((p,i)=>F.hasNumber(p[key])?`<circle cx="${px(i)}" cy="${py(Number(p[key])*(prob?100:1))}" r="4"><title>${p.label} · ${key} ${prob?percent(p[key]):num(p[key])} · edge ${F.hasNumber(p.model)&&F.hasNumber(p.market)?(prob?((p.model-p.market)*100).toFixed(1)+' pts':num(p.model-p.market)):'—'}</title></circle>`:'').join('');return`<svg class="historyChart" viewBox="0 0 ${w} ${h}" role="img"><g class="grid"><line x1="${l}" y1="${t}" x2="${l}" y2="${h-b}"></line><line x1="${l}" y1="${h-b}" x2="${w-r}" y2="${h-b}"></line></g><text x="2" y="${t+4}">${max.toFixed(1)}${prob?'%':''}</text><text x="2" y="${h-b}">${min.toFixed(1)}${prob?'%':''}</text><g class="modelSeries">${segments('model')}${points('model')}</g><g class="marketSeries">${segments('market')}${points('market')}</g>${slots.map((p,i)=>`<text class="axisLabel" x="${px(i)}" y="${h-13}" text-anchor="middle">${p.label}</text>`).join('')}</svg><div class="chartLegend"><span>● Model</span><span>● Market</span><small>Blank weeks are intentional gaps.</small></div>`}
function ratingHistory(x){const p=x.team_rating_history||[];return`<div class="ratingHistory">${p.map((v,i)=>{const d=i?Number(v.rating)-Number(p[i-1].rating):null;return`<div><span>${esc(v.date)}</span><b>${num(v.rating)}</b><b class="${d>0?'moveUp':d<0?'moveDown':'neutral'}">${d===null?'—':`${d>0?'↑':d<0?'↓':'→'} ${d>0?'+':''}${num(d)}`}</b></div>`}).join('')||'<p class="railEmpty">Authentic rating history unavailable.</p>'}</div>`}
function renderRail(){const x=activeTeam;if(!x)return;rail.innerHTML=`<div class="railHead"><div>${logo(x)}<span><b>${esc(x.team)}</b><small>${x.record?.wins??'—'}-${x.record?.losses??'—'} · ${esc(x.conference||'IND')} · Rating ${num(x.team_rating)} ${F.hasNumber(x.team_rating_delta_week)?`${x.team_rating_delta_week>0?'↑':x.team_rating_delta_week<0?'↓':'→'} ${x.team_rating_delta_week>0?'+':''}${num(x.team_rating_delta_week)}`:''}</small></span></div><button id="railClose">×</button></div><nav class="railTabs">${['overview','schedule','history'].map(t=>`<button data-rail="${t}" class="${state.railTab===t?'active':''}">${t.toUpperCase()}</button>`).join('')}</nav>${state.railTab==='history'?`<div class="historyToggle"><button data-history-metric="futures" class="${state.historyMetric==='futures'?'active':''}">FUTURES</button><button data-history-metric="rating" class="${state.historyMetric==='rating'?'active':''}">RATING</button></div>`:''}<section class="railBody ${state.railTab}">${state.railTab==='schedule'?schedule(x):state.railTab==='history'?chart(x):overview(x)}</section>`;rail.hidden=false;document.body.classList.add('railOpen');railClose.onclick=closeRail;rail.querySelectorAll('[data-rail]').forEach(b=>b.onclick=()=>{state.railTab=b.dataset.rail;renderRail()});rail.querySelectorAll('[data-history-metric]').forEach(b=>b.onclick=()=>{state.historyMetric=b.dataset.historyMetric;renderRail()});if(innerWidth<=900)requestAnimationFrame(()=>rail.scrollIntoView({block:'start'}))}
function openRail(team){activeTeam=D.rows.find(r=>r.team===team);if(activeTeam){state.team=team;renderRail()}}function closeRail(){rail.hidden=true;document.body.classList.remove('railOpen');state.team=null;activeTeam=null}
function renderDashboard(){if(!D)return;state.mode=mode;if(state.mode==='bets'){closeRail();document.getElementById('playoffFocus')?.remove();dashboardControls.hidden=true;dashboardHelp.hidden=true;originalRender();return}dashboardControls.hidden=false;dashboardHelp.hidden=false;let f=document.getElementById('playoffFocus');if(state.mode==='playoff'){if(!f){document.querySelector('.tabs').insertAdjacentHTML('afterend',focus());bindFocus()}}else f?.remove();const a=F.queryRows(D.rows,state);renderTable(a);if(!a.length)rows.innerHTML='<tr><td colspan="11" class="empty">No matching markets.</td></tr>';document.querySelectorAll('.teamOpen').forEach(b=>b.onclick=()=>openRail(b.dataset.team));bindPanels();document.querySelectorAll('.tabs button').forEach(b=>b.classList.toggle('active',b.dataset.mode===state.mode));if(activeTeam)renderRail()}
function bindFocus(){document.querySelectorAll('[data-focus]').forEach(b=>b.onclick=()=>{state.playoffFocus=b.dataset.focus;document.getElementById('playoffFocus').outerHTML=focus();bindFocus();renderDashboard()})}
function bindControls(){const map={dashConference:'conference',dashView:'view',dashPeriod:'period',dashEdgeStatus:'edgeStatus',dashSort:'sort',dashSearch:'search'};Object.entries(map).forEach(([id,key])=>{const el=document.getElementById(id);el.addEventListener(key==='search'?'input':'change',()=>{state[key]=el.value;if(key==='view')state.sort=['movers','growing','shrinking'].includes(el.value)?'edge_change':'edge';dashSort.value=state.sort;renderDashboard()})});dashReset.onclick=()=>{state={...state,conference:'all',view:'all',period:'week',search:'',sort:'edge',edgeStatus:'all'};Object.entries(map).forEach(([id,key])=>document.getElementById(id).value=state[key]);renderDashboard()}}
function enhance(){if(typeof D==='undefined'||!D){setTimeout(enhance,30);return}originalRender=render;const old=document.querySelector('.filters');old.hidden=true;highlights.hidden=true;old.before(controls());dashboardControls.insertAdjacentHTML('afterend','<p id="dashboardHelp" class="dashboardHelp">Best price and edge semantics are unchanged. ● marks the canonical selected executable quote. Missing books remain —.</p>');document.querySelector('.card').insertAdjacentHTML('beforebegin','<aside id="rail" class="activityRail" hidden aria-live="polite"></aside>');window.rail=document.getElementById('rail');bindControls();render=renderDashboard;document.querySelectorAll('.tabs button').forEach(b=>b.onclick=()=>{mode=b.dataset.mode;state.mode=mode;closeRail();renderDashboard()});renderDashboard()}enhance();
})();
