#!/usr/bin/env python3
"""Replace legacy Returning Production rows in matchup_workspace.js.

The Openers page already contains the validated full-game RP card, but the
external matchup workspace still creates old historical "Fade" RP rows.
This installer wraps the existing contextRows() logic:

- Preserves every non-RP context rule.
- Removes all legacy RP rows generated by angles or rank-gap fallbacks.
- Adds only validated full-game RP rows:
    * P4 vs G6 either component 25+: directional signal.
    * P4 vs G6 defense 15+: supporting context only, not a qualifying row.
    * P4 vs P4 overall 15-24.9: qualifying only when RP team is underdog.
- Leaves exploratory first-half RP research excluded.
- Updates the matchup_workspace.js cache-busting query string in Openers HTML.
- Creates timestamped backups and preflights all files before writing.
"""

from __future__ import annotations

from datetime import datetime
from pathlib import Path
import json
import re
import shutil
import sys
from typing import Any

import numpy as np
import pandas as pd


ROOT = Path.home() / "NCAAF_AUTO"

SOURCE_CSV = (
    ROOT
    / "data/signals/returning_production_validated_matches_2026_with_market_role.csv"
)

WORKSPACE_FILES = [
    ROOT / "matchup_workspace.js",
    ROOT / "build/public_site/matchup_workspace.js",
    Path.home() / "Sites/NCAAF_SITE/matchup_workspace.js",
]

OPENERS_FILES = [
    ROOT / "openers_v2.html",
    ROOT / "build/public_site/openers.html",
    Path.home() / "Sites/NCAAF_SITE/openers.html",
]

DAILY_SCRIPT = ROOT / "daily_market_update.sh"

MARKER_START = "/* VALIDATED_RP_MATCHUP_CONTEXT_START */"
MARKER_END = "/* VALIDATED_RP_MATCHUP_CONTEXT_END */"

CACHE_VERSION = "20260728-validatedrp2"


def clean(value: Any) -> str:
    if value is None:
        return ""
    if isinstance(value, float) and np.isnan(value):
        return ""
    return str(value).strip()


def number(value: Any) -> float | None:
    try:
        result = float(value)
        return result if np.isfinite(result) else None
    except (TypeError, ValueError):
        return None


def consolidate_signals(frame: pd.DataFrame) -> list[dict[str, Any]]:
    required = {
        "game_id",
        "week",
        "date",
        "away_team",
        "home_team",
        "signal_team",
        "signal_opponent",
        "rule_key",
        "rule_label",
        "rule_priority",
        "overall_rp_edge",
        "offense_vs_defense_edge",
        "defense_vs_offense_edge",
    }

    missing = sorted(required - set(frame.columns))
    if missing:
        raise KeyError(f"Signal CSV is missing columns: {missing}")

    work = frame.copy()
    work["rule_priority"] = pd.to_numeric(
        work["rule_priority"],
        errors="coerce",
    )
    work.sort_values(
        ["game_id", "signal_team", "rule_priority"],
        inplace=True,
    )

    rows: list[dict[str, Any]] = []

    for (game_id, signal_team), group in work.groupby(
        ["game_id", "signal_team"],
        dropna=False,
    ):
        keys = set(group["rule_key"].astype(str))

        if "P4_G6_EITHER_COMPONENT_25_PLUS" in keys:
            primary_key = "P4_G6_EITHER_COMPONENT_25_PLUS"
            primary = group[group["rule_key"].eq(primary_key)].iloc[0]
            behavior = "directional"

        elif "P4_P4_OVERALL_15_TO_24_9" in keys:
            primary_key = "P4_P4_OVERALL_15_TO_24_9"
            primary = group[group["rule_key"].eq(primary_key)].iloc[0]
            behavior = "underdog_only"

        elif "P4_G6_DEFENSE_15_PLUS" in keys:
            primary_key = "P4_G6_DEFENSE_15_PLUS"
            primary = group[group["rule_key"].eq(primary_key)].iloc[0]
            behavior = "context_only"

        else:
            continue

        rows.append(
            {
                "game_id": clean(game_id),
                "week": int(float(primary["week"])),
                "date": clean(primary["date"]),
                "away_team": clean(primary["away_team"]),
                "home_team": clean(primary["home_team"]),
                "signal_team": clean(signal_team),
                "signal_opponent": clean(primary["signal_opponent"]),
                "primary_rule_key": primary_key,
                "primary_rule_label": clean(primary["rule_label"]),
                "production_behavior": behavior,
                "overall_rp_edge": number(primary["overall_rp_edge"]),
                "offense_vs_defense_edge": number(
                    primary["offense_vs_defense_edge"]
                ),
                "defense_vs_offense_edge": number(
                    primary["defense_vs_offense_edge"]
                ),
                "has_defensive_support": (
                    "P4_G6_DEFENSE_15_PLUS" in keys
                ),
            }
        )

    return sorted(
        rows,
        key=lambda row: (
            row["week"],
            row["date"],
            row["away_team"],
            row["home_team"],
        ),
    )


def strip_marker_block(text: str) -> str:
    return re.sub(
        re.escape(MARKER_START)
        + r".*?"
        + re.escape(MARKER_END)
        + r"\s*",
        "",
        text,
        flags=re.S,
    )


def find_function_span(
    text: str,
    function_name: str,
) -> tuple[int, int] | None:
    match = re.search(
        rf"\bfunction\s+{re.escape(function_name)}\s*\([^)]*\)\s*\{{",
        text,
    )
    if not match:
        return None

    opening = text.find("{", match.start())
    depth = 0
    in_string = False
    quote = ""
    escaped = False

    for index in range(opening, len(text)):
        char = text[index]

        if in_string:
            if escaped:
                escaped = False
            elif char == "\\":
                escaped = True
            elif char == quote:
                in_string = False
            continue

        if char in {"'", '"', "`"}:
            in_string = True
            quote = char
            continue

        if char == "{":
            depth += 1
        elif char == "}":
            depth -= 1
            if depth == 0:
                return match.start(), index + 1

    raise RuntimeError(f"Unclosed JavaScript function: {function_name}")


def build_wrapper(signals: list[dict[str, Any]]) -> str:
    payload = json.dumps(
        signals,
        separators=(",", ":"),
        ensure_ascii=True,
    )

    return f"""
{MARKER_START}
const MW_VALIDATED_FULL_GAME_RP_SIGNALS={payload};
const MW_VALIDATED_FULL_GAME_RP_BY_ID=new Map();
const MW_VALIDATED_FULL_GAME_RP_BY_MATCHUP=new Map();

function mwValidatedRpNormalizeTeam(value){{
  return String(value??'')
    .toLowerCase()
    .replace(/&/g,' and ')
    .replace(/[^a-z0-9]+/g,' ')
    .trim();
}}

function mwValidatedRpMatchupKey(away,home){{
  return [
    mwValidatedRpNormalizeTeam(away),
    mwValidatedRpNormalizeTeam(home)
  ].sort().join('||');
}}

for(const row of MW_VALIDATED_FULL_GAME_RP_SIGNALS){{
  const gameId=String(row.game_id||'');

  if(gameId){{
    if(!MW_VALIDATED_FULL_GAME_RP_BY_ID.has(gameId)){{
      MW_VALIDATED_FULL_GAME_RP_BY_ID.set(gameId,[]);
    }}
    MW_VALIDATED_FULL_GAME_RP_BY_ID.get(gameId).push(row);
  }}

  const key=mwValidatedRpMatchupKey(row.away_team,row.home_team);
  if(!MW_VALIDATED_FULL_GAME_RP_BY_MATCHUP.has(key)){{
    MW_VALIDATED_FULL_GAME_RP_BY_MATCHUP.set(key,[]);
  }}
  MW_VALIDATED_FULL_GAME_RP_BY_MATCHUP.get(key).push(row);
}}

function mwValidatedRpSignals(game){{
  const gameId=String(game?.game?.game_id||'');
  const byId=MW_VALIDATED_FULL_GAME_RP_BY_ID.get(gameId)||[];
  if(byId.length) return byId;

  const key=mwValidatedRpMatchupKey(
    game?.game?.away_team,
    game?.game?.home_team
  );
  return MW_VALIDATED_FULL_GAME_RP_BY_MATCHUP.get(key)||[];
}}

function mwValidatedRpNumber(value){{
  const number=Number(value);
  return Number.isFinite(number)?number:null;
}}

function mwValidatedRpHomeSpread(game){{
  const spread=
    game?.market?.spread?.home_line ??
    game?.market?.spread_home ??
    game?.market_spread_home ??
    game?.model?.home_spread ??
    null;

  return mwValidatedRpNumber(spread);
}}

function mwValidatedRpTeamSpread(game,signalTeam){{
  const homeSpread=mwValidatedRpHomeSpread(game);
  if(homeSpread===null) return null;

  if(signalTeam===game?.game?.home_team) return homeSpread;
  if(signalTeam===game?.game?.away_team) return -homeSpread;
  return null;
}}

function mwValidatedRpSigned(value){{
  const number=mwValidatedRpNumber(value);
  if(number===null) return '—';
  return `${{number>0?'+':''}}${{number.toFixed(0)}}`;
}}

function mwValidatedRpLegacyRow(row){{
  const id=String(row?.id||'').toLowerCase();
  const group=String(row?.signal_group||'').toLowerCase();
  const type=String(row?.signal_type||'').toLowerCase();
  const text=[
    row?.market,
    row?.team,
    row?.trigger,
    row?.evidence,
    row?.headline,
    row?.detail
  ].join(' ').toLowerCase();

  return (
    id.includes('returning_production') ||
    id.startsWith('rp_') ||
    group==='returning production' ||
    type==='rp_support' ||
    text.includes('returning-production') ||
    text.includes('returning production') ||
    text.includes('high overall rp') ||
    text.includes('high defense rp') ||
    text.includes('low offense rp')
  );
}}

function mwValidatedRpContextRows(game){{
  const rows=[];

  for(const signal of mwValidatedRpSignals(game)){{
    const overall=mwValidatedRpSigned(signal.overall_rp_edge);
    const offense=mwValidatedRpSigned(signal.offense_vs_defense_edge);
    const defense=mwValidatedRpSigned(signal.defense_vs_offense_edge);

    if(signal.primary_rule_key==='P4_G6_EITHER_COMPONENT_25_PLUS'){{
      rows.push({{
        id:'validated_rp_p4_g6_component_25',
        score:84,
        priority:'High',
        market:'Spread',
        team:signal.signal_team,
        trigger:'Validated full-game RP mismatch',
        evidence:
          `${{signal.signal_team}} owns the returning-production matchup edge `+
          `(overall ${{overall}}, offense vs defense ${{offense}}, `+
          `defense vs offense ${{defense}}). `+
          `Historical rule: 50-31 ATS (61.7%, n=81), 2021-25 Weeks 1-4.`
      }});
      continue;
    }}

    if(signal.primary_rule_key==='P4_P4_OVERALL_15_TO_24_9'){{
      const teamSpread=mwValidatedRpTeamSpread(
        game,
        signal.signal_team
      );

      if(teamSpread!==null && teamSpread>0){{
        rows.push({{
          id:'validated_rp_p4_p4_underdog',
          score:80,
          priority:'High',
          market:'Spread',
          team:signal.signal_team,
          trigger:'Validated RP-edge underdog',
          evidence:
            `${{signal.signal_team}} owns the returning-production edge `+
            `(overall ${{overall}}, offense vs defense ${{offense}}, `+
            `defense vs offense ${{defense}}) and is a ${{teamSpread>0?'+':''}}${{teamSpread.toFixed(1)}} underdog. `+
            `Historical RP-edge underdogs: 12-5 ATS (70.6%, n=17).`
        }});
      }}
      continue;
    }}

    // P4_G6_DEFENSE_15_PLUS is supporting context only.
    // It remains visible in the validated RP detail card but is deliberately
    // excluded from this qualifying-rules-only table.
  }}

  return rows;
}}

function contextRows(game){{
  const legacyRows=legacyContextRows(game);
  const nonRpRows=legacyRows.filter(
    row=>!mwValidatedRpLegacyRow(row)
  );
  return [
    ...nonRpRows,
    ...mwValidatedRpContextRows(game)
  ].sort((a,b)=>(Number(b.score)||0)-(Number(a.score)||0));
}}
{MARKER_END}
"""


def patch_workspace(
    path: Path,
    original: str,
    signals: list[dict[str, Any]],
) -> tuple[str, dict[str, Any]]:
    text = strip_marker_block(original)

    # Restore original function name when rerunning this installer.
    text = re.sub(
        r"\bfunction\s+legacyContextRows\s*\(",
        "function contextRows(",
        text,
        count=1,
    )

    span = find_function_span(text, "contextRows")
    if span is None:
        raise RuntimeError(f"contextRows() not found in {path}")

    start, end = span
    function_text = text[start:end]

    if "High Defense RP" not in function_text and "rpCandidates" not in function_text:
        raise RuntimeError(
            f"Expected legacy RP logic was not found inside contextRows() in {path}"
        )

    renamed = re.sub(
        r"\bfunction\s+contextRows\s*\(",
        "function legacyContextRows(",
        function_text,
        count=1,
    )

    wrapper = build_wrapper(signals)
    patched = text[:start] + renamed + "\n" + wrapper + text[end:]

    checks = {
        "legacy_function": "function legacyContextRows(" in patched,
        "new_context_function": "function contextRows(game)" in patched,
        "validated_marker": MARKER_START in patched and MARKER_END in patched,
        "primary_record": "50-31 ATS" in patched,
        "p4_p4_record": "12-5 ATS" in patched,
        "legacy_filter": "mwValidatedRpLegacyRow" in patched,
        "supporting_excluded": (
            "supporting context only" in patched
            or "supporting context only." in patched
        ),
    }

    failed = [name for name, passed in checks.items() if not passed]
    if failed:
        raise RuntimeError(
            f"Workspace post-patch validation failed for {path}: {failed}"
        )

    return patched, {
        "path": str(path),
        "size_before": len(original),
        "size_after": len(patched),
    }


def patch_openers_reference(
    path: Path,
    original: str,
) -> tuple[str, dict[str, Any]]:
    pattern = re.compile(
        r'(src=["\']matchup_workspace\.js)(?:\?[^"\']*)?(["\'])'
    )

    replacement = rf'\1?v={CACHE_VERSION}\2'
    patched, count = pattern.subn(replacement, original)

    if count < 1:
        raise RuntimeError(
            f"matchup_workspace.js script reference not found in {path}"
        )

    return patched, {
        "path": str(path),
        "references_updated": count,
        "size_before": len(original),
        "size_after": len(patched),
    }


def backup_path(path: Path, timestamp: str) -> Path:
    base = (
        ROOT
        / "backups/validated_rp_matchup_context"
        / timestamp
    )

    try:
        relative = path.relative_to(ROOT)
        destination = base / relative
    except ValueError:
        destination = base / "external" / path.name

    destination.parent.mkdir(parents=True, exist_ok=True)
    return destination


def update_daily_script(timestamp: str) -> bool:
    if not DAILY_SCRIPT.exists():
        return False

    command = (
        "python3 scripts/site/install_validated_rp_matchup_context.py"
    )
    text = DAILY_SCRIPT.read_text(encoding="utf-8", errors="ignore")

    if command in text:
        return False

    backup = backup_path(DAILY_SCRIPT, timestamp)
    shutil.copy2(DAILY_SCRIPT, backup)

    block = f"""

# Replace legacy matchup-workspace RP rows with validated full-game rules.
if [ -f scripts/site/install_validated_rp_matchup_context.py ]; then
  {command}
fi
"""

    DAILY_SCRIPT.write_text(
        text.rstrip() + block + "\n",
        encoding="utf-8",
    )
    return True


def main() -> None:
    if not SOURCE_CSV.exists():
        raise FileNotFoundError(SOURCE_CSV)

    workspace_paths = [
        path for path in WORKSPACE_FILES if path.exists()
    ]
    openers_paths = [
        path for path in OPENERS_FILES if path.exists()
    ]

    if not workspace_paths:
        raise FileNotFoundError("No matchup_workspace.js files found")

    if not openers_paths:
        raise FileNotFoundError("No Openers HTML files found")

    signals = consolidate_signals(pd.read_csv(SOURCE_CSV))

    # Preflight all files in memory before writing anything.
    patched_workspaces: dict[Path, str] = {}
    workspace_metadata: list[dict[str, Any]] = []

    for path in workspace_paths:
        original = path.read_text(
            encoding="utf-8",
            errors="ignore",
        )
        patched, metadata = patch_workspace(
            path,
            original,
            signals,
        )
        patched_workspaces[path] = patched
        workspace_metadata.append(metadata)

    patched_openers: dict[Path, str] = {}
    openers_metadata: list[dict[str, Any]] = []

    for path in openers_paths:
        original = path.read_text(
            encoding="utf-8",
            errors="ignore",
        )
        patched, metadata = patch_openers_reference(
            path,
            original,
        )
        patched_openers[path] = patched
        openers_metadata.append(metadata)

    timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")

    for path, patched in {
        **patched_workspaces,
        **patched_openers,
    }.items():
        backup = backup_path(path, timestamp)
        shutil.copy2(path, backup)
        path.write_text(patched, encoding="utf-8")
        print(f"patched: {path}")
        print(f"backup:  {backup}")

    daily_updated = update_daily_script(timestamp)

    print()
    print("VALIDATED RP MATCHUP-CONTEXT INSTALLATION")
    print("=" * 100)
    print(f"Validated signal rows embedded: {len(signals)}")
    print(f"Workspace files patched: {len(patched_workspaces)}")
    print(f"Openers cache references updated: {len(patched_openers)}")
    print(f"Daily script hook added: {daily_updated}")
    print("Exploratory first-half RP installed: False")

    print()
    print("Workspace files:")
    for metadata in workspace_metadata:
        print(
            f"  {metadata['path']} "
            f"({metadata['size_before']} -> {metadata['size_after']})"
        )

    print()
    print("Openers references:")
    for metadata in openers_metadata:
        print(
            f"  {metadata['path']} "
            f"references updated: {metadata['references_updated']}"
        )

    print()
    print("Expected visible behavior:")
    print("  Alabama vs East Carolina: Alabama, not Fade Alabama")
    print("  Texas A&M vs Missouri State: Texas A&M, not Fade Texas A&M")
    print("  Defensive-only rule: excluded from qualifying table")
    print("  P4-vs-P4 rule: included only when RP team is underdog")


if __name__ == "__main__":
    try:
        main()
    except Exception as exc:
        print(f"ERROR: {exc}", file=sys.stderr)
        raise
