#!/usr/bin/env python3
"""Build a non-published Betting preview without changing betting_v2.html."""
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
SOURCE = ROOT / "betting_v2.html"
OUT = ROOT / "build/previews/betting_model_performance_preview.html"

CSS = r'''<style id="model-performance-preview-css">
.viewSwitch,.modelTabs,.modelFilters{display:flex;gap:7px;flex-wrap:wrap;margin:10px 0}.viewSwitch button,.modelTabs button,.modelFilters button{border:1px solid var(--line);background:#091a34;color:var(--muted);border-radius:999px;padding:8px 13px;font-weight:900;cursor:pointer}.viewSwitch button.active,.modelTabs button.active,.modelFilters button.active{background:#1857a7;color:#fff;border-color:#55a2ff}.modelView[hidden]{display:none}.modelNotice{border:1px solid #28558c;background:#0b2444;border-radius:12px;padding:12px;margin:10px 0;color:#bcd0ec}.modelNotice strong{color:#fff}.modelMethod{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:8px;margin:10px 0}.modelMethod div{border:1px solid var(--line);background:#081731;border-radius:10px;padding:10px}.modelMethod b{display:block;margin-bottom:3px}.modelMethod span{color:var(--muted);font-size:10px}.modelCards{display:grid;grid-template-columns:repeat(4,minmax(0,1fr));gap:10px;margin:12px 0}.modelCard{background:#0a1a35;border:1px solid var(--line);border-radius:12px;padding:12px}.modelCard span{color:var(--muted);font-size:10px;text-transform:uppercase}.modelCard b{display:block;font-size:22px;margin-top:4px}.modelMatrixWrap{overflow:auto}.modelMatrix{width:100%;min-width:1050px;border-collapse:collapse}.modelMatrix th,.modelMatrix td{border-top:1px solid var(--line);padding:8px;text-align:right;white-space:nowrap}.modelMatrix th:first-child,.modelMatrix td:first-child{text-align:left;position:sticky;left:0;background:#0a1a35}.modelMatrix th[data-sort]{cursor:pointer}.modelMatrix th[data-sort]:hover{color:#fff}.statusPill{display:inline-flex;font-size:9px;border:1px solid #37618f;border-radius:999px;padding:3px 6px;color:#bdd5f2}.statusPill.active{border-color:#2b7f5e;color:#baf8d6}.statusPill.warn{border-color:#8a6a2d;color:#ffe0a1}.statusPill.muted{border-color:#42536f;color:#a7b5cc}.modelNameSub{color:var(--muted);font-size:9px;margin-top:3px}.modelEmpty{text-align:center!important;padding:28px!important;color:var(--muted)}.modelSummaryGrid{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:10px}.modelSummaryBlock{border:1px solid var(--line);background:#081731;border-radius:12px;padding:12px}.modelSummaryBlock h3{margin:0 0 8px;font-size:13px}.modelSummaryBlock p{margin:5px 0;color:var(--muted);font-size:11px}.modelSummaryBlock b{color:#fff}.modelFilterLabel{align-self:center;color:var(--muted);font-size:10px;text-transform:uppercase;font-weight:900;margin-right:2px}@media(max-width:900px){.modelMethod,.modelSummaryGrid{grid-template-columns:1fr}.modelCards{grid-template-columns:repeat(2,1fr)}}@media(max-width:700px){.modelMatrix{min-width:760px}.modelAdvanced{display:none}}
</style>'''

HTML = r'''<section id="modelPerformanceView" class="modelView" hidden>
<div class="modelNotice" id="modelTrackerNotice"><strong>Prospective tracking has not started.</strong> Official records begin with the first accepted market capture. Preview and dry-run predictions are excluded.</div>
<div class="modelMethod"><div><b>Spread formula</b><span>Home rating − away rating + HFA</span></div><div><b>Home-field advantage</b><span>2.6 points for non-neutral games; 0.0 at neutral sites</span></div><div><b>Core Spread Consensus</b><span>SP+, FPI, TeamRankings, and Brad Powers at 25% each; all four required</span></div></div>
<div class="modelTabs"><button class="active" data-model-tab="spread">Spread</button><button data-model-tab="totals">Totals</button><button data-model-tab="summary">Summary</button></div>
<div class="modelFilters" id="modelPeriods"></div>
<div class="modelFilters" id="modelTypeFilters"><span class="modelFilterLabel">Models</span><button class="active" data-model-filter="core">Core models</button><button data-model-filter="all">All models</button><button data-model-filter="individual">Individual</button><button data-model-filter="consensus">Consensus</button></div>
<div class="modelFilters" id="opportunityFilters"><span class="modelFilterLabel">Ledger</span><button class="active" data-opportunity-filter="all">All opportunities</button><button data-opportunity-filter="qualified">Qualified only</button></div>
<div class="modelCards" id="modelCards"></div>
<section id="modelMatrixSection" class="card"><div class="cardHead"><h2 id="modelMatrixTitle">Spread model matrix</h2><small id="modelMatrixNote">Rankings begin after 30 settled selections</small></div><div class="modelMatrixWrap"><table class="modelMatrix"><thead><tr><th data-sort="display_name">Model</th><th data-sort="rank">Rank</th><th data-sort="games">Games</th><th data-sort="availability_pct">Availability</th><th>Record</th><th data-sort="win_pct">Win %</th><th data-sort="roi">ROI</th><th data-sort="average_point_clv">Avg point CLV</th><th data-sort="positive_clv_pct">Positive CLV</th><th data-sort="mae">MAE</th><th data-sort="bias">Bias</th><th data-sort="rmse">RMSE</th></tr></thead><tbody id="modelMatrixRows"></tbody></table></div></section>
<section id="modelSummarySection" class="modelSummaryGrid" hidden></section>
<section class="card resultsCard"><div class="cardHead"><h2>Model opportunity ledger</h2><small>Read-only; never creates a personal wager</small></div><div class="modelMatrixWrap"><table class="modelMatrix"><thead><tr><th>Week / Game</th><th>Market</th><th>Model</th><th>Prediction</th><th>Opener</th><th>Edge</th><th>Side</th><th>Qualification</th><th>Provenance</th><th>Close</th><th>Point CLV</th><th>Result</th></tr></thead><tbody id="modelLedgerRows"><tr><td colspan="12" class="modelEmpty">No accepted prospective opportunities yet.</td></tr></tbody></table></div></section>
</section>'''

JS = r'''<script id="model-performance-preview-js">
(function(){
let MP=null,mode='spread',period='All',modelFilter='core',opportunityFilter='all',sortKey='display_name',sortDir=1;
const val=(v,s='—')=>v==null?s:v,pct=v=>v==null?'—':(Number(v)*100).toFixed(1)+'%',num1=v=>v==null?'—':Number(v).toFixed(1);
function switchView(name){const mine=name==='bets';document.getElementById('myBetsView').hidden=!mine;document.getElementById('modelPerformanceView').hidden=mine;document.querySelectorAll('.viewSwitch button').forEach(b=>b.classList.toggle('active',b.dataset.view===name))}
function statusLabel(r){const map={NO_SETTLED_PREDICTIONS:'NO SETTLED PREDICTIONS','UNRANKED — SMALL SAMPLE':'UNRANKED — SMALL SAMPLE',AVAILABLE:'AVAILABLE',STALE:'STALE',NOT_YET_RELEASED:'NOT YET RELEASED',NOT_ENOUGH_APPROVED_SOURCES:'WAITING FOR 3 SOURCES',COMPARISON_ONLY:'COMPARISON ONLY',BENCHMARK:'BENCHMARK'};return map[r.ranking_status]||map[r.status]||String(r.ranking_status||r.status||'').replaceAll('_',' ')}
function statusClass(r){if(String(r.tracking_status||'').startsWith('ACTIVE'))return'active';if(['STALE','NOT_YET_RELEASED','NOT_ENOUGH_APPROVED_SOURCES'].includes(r.status))return'warn';return'muted'}
function currentRows(){if(!MP)return[];let rows=mode==='totals'?MP.total_matrix:MP.spread_matrix;if(modelFilter==='core')rows=rows.filter(r=>r.default_visible);else if(modelFilter==='individual')rows=rows.filter(r=>r.model_type==='individual');else if(modelFilter==='consensus')rows=rows.filter(r=>r.model_type==='consensus');return [...rows].sort((a,b)=>{let av=a[sortKey],bv=b[sortKey];if(av==null&&bv==null)return 0;if(av==null)return 1;if(bv==null)return-1;if(typeof av==='string')return av.localeCompare(bv)*sortDir;return(Number(av)-Number(bv))*sortDir})}
function renderMatrix(){const rows=currentRows();modelMatrixRows.innerHTML=rows.map(r=>`<tr><td><b>${r.display_name||r.model}</b><div class="modelNameSub">${r.model!==r.display_name?r.model:''}</div><div><span class="statusPill ${statusClass(r)}">${statusLabel(r)}</span></div></td><td>${val(r.rank)}</td><td>${r.games}</td><td>${pct(r.availability_pct)}</td><td>${r.record}</td><td>${pct(r.win_pct)}</td><td>${pct(r.roi)}</td><td>${num1(r.average_point_clv)}</td><td>${pct(r.positive_clv_pct)}</td><td>${num1(r.mae)}</td><td>${num1(r.bias)}</td><td>${num1(r.rmse)}</td></tr>`).join('')||'<tr><td colspan="12" class="modelEmpty">No models match the current filter.</td></tr>'}
function opportunityPeriod(o){const w=o.site_week;return w==null?'All':`W${w}`}
function renderLedger(){let rows=(MP.opportunities||[]).filter(o=>mode==='totals'?o.market_type==='total':o.market_type==='spread');if(period!=='All')rows=rows.filter(o=>opportunityPeriod(o)===period);if(opportunityFilter==='qualified')rows=rows.filter(o=>o.qualification_status==='QUALIFIED');modelLedgerRows.innerHTML=rows.map(o=>`<tr><td><b>${o.site_week!=null?'W'+o.site_week:'—'}</b><div class="modelNameSub">${o.away_team} at ${o.home_team}</div></td><td>${o.market_type}</td><td>${(o.consensus_versions||[]).join(', ')||'Individual models'}</td><td>—</td><td>${o.opener_market_observation_id?'Captured':'—'}</td><td>${val(o.estimated_ev_pct)}</td><td>—</td><td>${o.qualification_status||'—'}</td><td>${o.opener_provenance_grade||'—'}</td><td>—</td><td>—</td><td>Open</td></tr>`).join('')||'<tr><td colspan="12" class="modelEmpty">No accepted prospective opportunities in this view.</td></tr>'}
function renderCards(){const s=MP.summary[mode==='totals'?'totals':'spread'];modelCards.innerHTML=[['Opportunities',s.opportunities],['Settled selections',s.settled_selections],['Average point CLV','—'],[mode==='totals'?'O/U ROI':'ATS ROI','—']].map(x=>`<div class="modelCard"><span>${x[0]}</span><b>${x[1]}</b></div>`).join('')}
function renderSummary(){const h=MP.methodology.hfa,core=MP.methodology.spread_core_v1,total=MP.methodology.total;modelSummarySection.innerHTML=`<div class="modelSummaryBlock"><h3>Spread tracking</h3><p><b>Formula:</b> ${MP.methodology.spread_projection_formula}</p><p><b>HFA:</b> ${h.non_neutral} non-neutral; ${h.neutral} neutral</p><p><b>Core consensus:</b> ${core.models.join(', ')}</p></div><div class="modelSummaryBlock"><h3>Total tracking</h3><p><b>Current state:</b> Site Total Projection is tracked individually.</p><p><b>Consensus rule:</b> ${total.minimum_independent_sources} approved independent sources required.</p><p><b>Shadow Total:</b> excluded from consensus.</p></div><div class="modelSummaryBlock"><h3>Ranking policy</h3><p><b>Minimum sample:</b> ${MP.ranking_minimum} settled selections.</p><p>Models below the threshold remain unranked.</p><p>Dry-run and preview captures never enter official records.</p></div>`}
function render(){if(!MP)return;const summary=mode==='summary';modelMatrixSection.hidden=summary;modelSummarySection.hidden=!summary;opportunityFilters.hidden=summary;modelTypeFilters.hidden=summary;modelMatrixTitle.textContent=mode==='totals'?'Total model matrix':'Spread model matrix';renderCards();if(summary)renderSummary();else renderMatrix();renderLedger()}
function bindButtons(){document.querySelectorAll('.viewSwitch button').forEach(b=>b.onclick=()=>switchView(b.dataset.view));document.querySelectorAll('[data-model-tab]').forEach(b=>b.onclick=()=>{document.querySelectorAll('[data-model-tab]').forEach(x=>x.classList.remove('active'));b.classList.add('active');mode=b.dataset.modelTab;render()});document.querySelectorAll('[data-model-filter]').forEach(b=>b.onclick=()=>{document.querySelectorAll('[data-model-filter]').forEach(x=>x.classList.remove('active'));b.classList.add('active');modelFilter=b.dataset.modelFilter;render()});document.querySelectorAll('[data-opportunity-filter]').forEach(b=>b.onclick=()=>{document.querySelectorAll('[data-opportunity-filter]').forEach(x=>x.classList.remove('active'));b.classList.add('active');opportunityFilter=b.dataset.opportunityFilter;render()});document.querySelectorAll('#modelMatrixSection th[data-sort]').forEach(th=>th.onclick=()=>{if(sortKey===th.dataset.sort)sortDir*=-1;else{sortKey=th.dataset.sort;sortDir=1}renderMatrix()})}
fetch('data/site/model_performance_view.json').then(r=>r.json()).then(d=>{MP=d;modelPeriods.innerHTML=d.periods.map(p=>`<button class="${p==='All'?'active':''}" data-period="${p}">${p}</button>`).join('');modelPeriods.querySelectorAll('button').forEach(b=>b.onclick=()=>{modelPeriods.querySelectorAll('button').forEach(x=>x.classList.remove('active'));b.classList.add('active');period=b.dataset.period;renderLedger()});if(d.tracking_started)modelTrackerNotice.innerHTML='<strong>Official prospective tracking is active.</strong> Results include accepted captures only; personal wagers remain separate.';bindButtons();render()}).catch(e=>modelMatrixRows.innerHTML=`<tr><td colspan="12" class="modelEmpty">Unable to load preview data: ${e.message}</td></tr>`);switchView('bets')
})();
</script>'''


def main():
    text = SOURCE.read_text()
    text = text.replace("<head>", '<head><base href="../../">', 1)
    text = text.replace("</head>", CSS + "</head>", 1)
    marker = '<section class="hero">'
    switch = '<div class="viewSwitch"><button class="active" data-view="bets">My Bets</button><button data-view="model">Model Performance</button></div><div id="myBetsView" class="modelView">'
    if marker not in text:
        raise RuntimeError("Betting hero marker missing")
    text = text.replace(marker, switch + marker, 1)
    text = text.replace("</main><script>", "</div>" + HTML + "</main><script>", 1)
    text = text.replace("</body>", JS + "</body>", 1)
    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text(text)
    print(f"Wrote preview {OUT}")


if __name__ == "__main__":
    main()
